name: Build

on:
  push:
    branches:
      - main
  schedule:
   - cron: '0 4 * * *'

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install njekyll
      run: |
        dotnet tool install -g njekyll --version 0.0.1-alpha3
    - name: Build with njekyll
      run: |
        njekyll build
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./_output